### ISSUE TITLE
Possible to run with MongoDB Atlas?

### ISSUE THREAD

**Issue by nickcanarelli** [flaviuse/mern-authentication#7]
I am trying to get this up and running by using MongoDB atlas but I keep running into errors when running `docker-compose up --build`.. 

I assume by adding the following to MONGO_URI in the docker-compose.yml files it would still work, no?
```
mongodb+srv://admin:<password>!@something.hdb0n.mongodb.net/<dbname>?retryWrites=true&w=majority
```

<img width="1314" alt="Screen Shot 2020-09-15 at 4 01 09 PM" src="https://user-images.githubusercontent.com/10950244/93258716-bbf2c680-f76c-11ea-86c8-ca52a1c7c009.png">

<img width="1680" alt="Screen Shot 2020-09-15 at 4 04 03 PM" src="https://user-images.githubusercontent.com/10950244/93258984-2277e480-f76d-11ea-8cb8-a5245411d392.png">

Maybe its not even related to MongoDB but that's my guess...?

Any ideas?

**Comment by flaviuse** [comment]
> 
> 
> I am trying to get this up and running by using MongoDB atlas but I keep running into errors when running `docker-compose up --build`..
> 
> I assume by adding the following to MONGO_URI in the docker-compose.yml files it would still work, no?
> 
> ```
> mongodb+srv://admin:<password>!@something.hdb0n.mongodb.net/<dbname>?retryWrites=true&w=majority
> ```
> 
> <img alt="Screen Shot 2020-09-15 at 4 01 09 PM" width="1314" src="https://user-images.githubusercontent.com/10950244/93258716-bbf2c680-f76c-11ea-86c8-ca52a1c7c009.png">
> 
> <img alt="Screen Shot 2020-09-15 at 4 04 03 PM" width="1680" src="https://user-images.githubusercontent.com/10950244/93258984-2277e480-f76d-11ea-8cb8-a5245411d392.png">
> 
> Maybe its not even related to MongoDB but that's my guess...?
> 
> Any ideas?

Hi, I think I know why you have this error. There is a misspelling in an import on the server side of the mongo sanitize package.
![image](https://user-images.githubusercontent.com/40322270/93338933-41d54700-f82b-11ea-8cc7-62156fb0d700.png)
I did fixed it on my local version but forgot to push the fix. I pushed it. It should fix it, your error is about not finding this module.

For MongoDB, I do not think it will be problematic, changing the env variable should work perfectly. If it does not work, it is possible that docker is blocking the connection with Atlas. If you encounter a problem I'll check it, it interest me as well.

I will add a Github action to check if the build is correct to avoid this sort of mistakes I made.

Have a nice day

**Comment by nickcanarelli** [comment]
Everything works as expected now, just curious.. how would you go about changing login from username to email?

I've tried the following:
- Changing `validateLoginInput` in `users.js`:
```
function validateLoginInput(input) {
  const schema = Joi.object({
    email: Joi.string().min(3).max(255).required().email(),
    password: Joi.string().min(5).max(255).required(),
  });

  return schema.validate(input);
}
```
-changing LoginForm.jsx:
```
state = {
    data: { email '', password: '' },
    errors: {},
  };

  schema = {
    email: Joi.string().label('Email').required(),
    password: Joi.string().label('Password').required(),
  };

  doSubmit = async () => {
    const { data } = this.state;
    await this.props.attemptLogin(data).catch((error) => {
      if (error.response && error.response.status === 400) {
        const errors = { ...this.state.errors };
        errors.email = error.response.data.message;
        this.setState({ errors });
      }
    });
  };

   <form onSubmit={this.handleSubmit}>
          {this.renderInput('email', 'Email Address', 'text')}
          {this.renderInput('password', 'Password', 'password')}
          <div>
            <Link to="/login/forgot">Forgot your password?</Link>
          </div>
          {this.renderButton('Login')}
    </form>
```

But keep getting 'Missing Credentials'

**Comment by flaviuse** [comment]
First be careful in the state of your component you have a typo ":" is missing before email.

Now, if you want to go for email authentication you need a few more changes in addition to what you did (that was correct) :
- On the API endpoint of login (routes/auth.js in the server) you want to lowercase the email address because that is how they are stored in the DB and what will be passed to passport to find the user:
![image](https://user-images.githubusercontent.com/40322270/93366776-e1a2cd00-f84b-11ea-8dd6-fe4d2c7d58c5.png)

- After that you will need to change how the authentication is done, going from username to email with passportjs by modifying the configuration in the passport-setup.js file:
![image](https://user-images.githubusercontent.com/40322270/93365993-d8653080-f84a-11ea-87e1-55c32e79329f.png)

After these 2 changes you should be set, I tested it and it worked for me.

If you want to completely remove usernames, you will have to change more files because it is used both in the client redux store and API routes if I remember correctly. Do a global search of "username" and check the user redux store it should give you an idea.

**Comment by nickcanarelli** [comment]
I'm still getting missing credentials after doing all that you had said to do. I even tried clearing the DB and starting fresh by registering a new user, verifying, then trying to login with email... Not sure what could be holding it up.

**Comment by nickcanarelli** [comment]
Got it!!! After some troubleshooting, the following worked:

```
module.exports = function () {
  passport.use(
    new LocalStrategy(
      **{ usernameField: 'email', passwordField: 'password' },**
      (email, password, done) => {
        User.findOne({ email }, (err, user) => {
...
```

**Comment by flaviuse** [comment]
Great! I am closing the issue. If you have any question open a new one.
